name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Packages
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-actions@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        CLEAN: true
